import axios from "axios"
const API = axios.create({baseURL:'https://expensive-undershirt-bee.cyclic.app'})
 
export const logIn = (authData) => API.post('/user/login',authData)
export const signUp = (authData) => API.post('/user/signup',authData)
export const getUsers = () => API.get('/user/getAllUsers')
export const getCurrentUser = (userId) => API.get(`/user/getUser/${userId}`)
export const updateUser = (id,updateData) => API.patch(`/user/update/${id}`,updateData)
export const postQuestion = (questionData) => API.post('/questions/Ask',questionData)
export const getQuestion = () => API.get('/questions/get')
export const deleteQuestion = (id) => API.delete(`/questions/delete/${id}`)
export const voteQuestion = (voteData) => API.patch('/questions/vote',voteData)
export const postAnswer = (id,answerData) => API.patch(`/answer/post/${id}`,answerData)
export const deleteAnswer = (deleteData) => API.patch('/answer/delete',deleteData)
export const postSubscription = (subscriptionData) => API.post('/subscription/post',subscriptionData)
export const getSubscription = () => API.get('/subscription/get')
export const chatbotAnswer = (chatbotData) => API.post('/chatbot/answer',chatbotData)
export const requestSend = (requestData) => API.post('/request/send',requestData)
export const requestGet = (id) => API.get(`/request/get/${id}`)
export const requestDelete = (id) => API.delete(`/request/delete/${id}`)
export const requestAccept = (requestData) => API.patch('/request/accept',requestData)
export const requestRemove = (requestData) => API.patch('/request/remove',requestData)
export const uploadPosts = (postData) => API.post('/posts/upload',postData)
export const uploadMedia = (formData,head) => API.post('/posts/media',formData,head)
export const getPosts = () => API.get('/posts/get')
export const setPostlikes = (postData) => API.patch('/posts/likes',postData)
export const postDelete = (id) => API.delete(`/posts/delete/${id}`)
